version: '3.5'

services:
  # node:
  #   build: .
  #   restart: unless-stopped
  #   depends_on:
  #     - db
  #   expose:
  #     - 4567 # use a reverse proxy like Traefik

  db:
    image: bitnami/mongodb:latest
    restart: unless-stopped
    expose:
      - 27017
    ports:
      - 27017:27017
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: nodebb
    volumes:
      - mongo:/data/db

volumes:
  mongo:
