version: '3.5'

services:
  db:
    image: postgres:14.4-alpine3.16
    restart: unless-stopped
    expose:
      - "5432"
    environment:
      POSTGRES_USER: nodebb
      POSTGRES_PASSWORD: nodebb
      POSTGRES_DB: nodebb
    volumes:
      - ./.docker/database/postgresql/data:/var/lib/postgresql/data
