version: '3.8'

services:
  nodebb:
    build: .
    restart: unless-stopped
    ports:
      - "4567:4567/tcp"
    volumes:
      - ./.docker/node_modules:/usr/src/app/node_modules
      - ./.docker/build:/usr/src/app/build
      - ./.docker/public/uploads:/usr/src/app/public/uploads
      - ./.docker:/opt/config
  mongo:
    image: "mongo:6-jammy"
    restart: unless-stopped
    expose:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: nodebb
      MONGO_INITDB_ROOT_PASSWORD: nodebb
      MONGO_INITDB_DATABASE: nodebb
    volumes:
      - ./.docker/database/mongo/config:/etc/mongo
      - ./.docker/database/mongo/data:/data/db
      - ./install/docker/mongodb-user-init.js:/docker-entrypoint-initdb.d/user-init.js
    profiles:
      - mongo
  postgres:
    image: postgres:16.0-alpine
    restart: unless-stopped
    expose:
      - "5432"
    environment:
      POSTGRES_USER: nodebb
      POSTGRES_PASSWORD: nodebb
      POSTGRES_DB: nodebb
    volumes:
      - ./.docker/database/postgresql/data:/var/lib/postgresql/data
    profiles:
      - postgres
  redis:
    image: redis:7.2.1-alpine
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - ./.docker/database/redis:/data
    profiles:
      - redis