version: '3.8'

services:
  nodebb:
    build: .
    restart: unless-stopped
    ports:
      - "4567:4567/tcp"
    volumes:
      - ./.docker/node_modules:/usr/src/app/node_modules
      - ./.docker/build:/usr/src/app/build
      - ./.docker/public/uploads:/usr/src/app/public/uploads
      - ./.docker:/opt/config
  mongo:
    image: "mongo:5.0.9-focal"
    restart: unless-stopped
    expose:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: nodebb
      MONGO_INITDB_ROOT_PASSWORD: nodebb
    volumes:
      - ./.docker/database/mongo/config:/etc/mongo
      - ./.docker/database/mongo/data:/data/db
    profiles:
      - mongo
  postgres:
    image: postgres:14.4-alpine3.16
    restart: unless-stopped
    expose:
      - "5432"
    environment:
      POSTGRES_USER: nodebb
      POSTGRES_PASSWORD: nodebb
      POSTGRES_DB: nodebb
    volumes:
      - ./.docker/database/postgresql/data:/var/lib/postgresql/data
    profiles:
      - postgres
  redis:
    image: redis:7.0.2-alpine3.16
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - ./.docker/database/redis:/data
    profiles:
      - redis