version: '3.5'

services:
  node:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "4567:4567/tcp"
    volumes:
      - user-dir:/mnt/nodebb/user-dir
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
  db:
    image: postgres:14.1-alpine3.15
    restart: unless-stopped
    expose:
      - 8080
    environment:
      POSTGRES_PASSWORD: nodebb
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
  user-dir: