version: '3.8'

services:
  nodebb:
    build: .
    restart: unless-stopped
    ports:
      - "4567:4567/tcp" # comment this out if you don't want to expose NodeBB to the host, or change the first number to any port you want
    # uncomment if you want to use another container as a reverse proxy
    # expose:
    #   - 4567
    volumes:
      - nodebb-build:/usr/src/app/build
      - nodebb-uploads:/usr/src/app/public/uploads
      - nodebb-config:/opt/config
      - ./install/docker/setup.json:/usr/src/app/setup.json
  mongo:
    image: "mongo:7-jammy"
    restart: unless-stopped
    expose:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: nodebb
      MONGO_INITDB_ROOT_PASSWORD: nodebb
      MONGO_INITDB_DATABASE: nodebb
    volumes:
      - mongo-config:/etc/mongo
      - mongo-data:/data/db
      - ./install/docker/mongodb-user-init.js:/docker-entrypoint-initdb.d/user-init.js
    profiles:
      - mongo
  postgres:
    image: postgres:16.1-alpine
    restart: unless-stopped
    expose:
      - "5432"
    environment:
      POSTGRES_USER: nodebb
      POSTGRES_PASSWORD: nodebb
      POSTGRES_DB: nodebb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    profiles:
      - postgres
  redis:
    image: redis:7.2.3-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes", "--loglevel", "warning"]
    # command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"] # uncomment if you want to use snapshotting instead of AOF
    expose:
      - "6379"
    volumes:
      - redis-data:/data
    profiles:
      - redis
volumes:
  mongo-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./.docker/database/mongo/data
  mongo-config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./.docker/database/mongo/config
  postgres-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./.docker/database/postgresql/data
  redis-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./.docker/database/redis
  nodebb-build:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./.docker/build
  nodebb-uploads:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./.docker/public/uploads
  nodebb-config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./.docker