version: '3.5'

services:
  nodebb:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "4567:4567/tcp"
    volumes:
      - ./.docker/node_modules:/usr/src/app/node_modules
      - ./.docker/build:/usr/src/app/build
      - ./.docker/public/uploads:/usr/src/app/public/uploads
      - ./.docker:/opt/config
